import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";

const mainFrontFamily = Poppins({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-family-main",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={mainFrontFamily.variable}>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
